name: Setup JDK 21, Scala, SBT

runs:
  using: 'composite'
  steps:
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'sbt'
    - name: Setup SBT & Scala
      uses: sbt/setup-sbt@v1
