name: CI - run tests on multiple machines

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  compilation:
    name: Compile the project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21, Scala, SBT
        uses: ./.github/actions/setup-scala
      - name: Compile
        uses: ./.github/actions/compile

  unit-tests-group-1:
    name: Run unit tests (1 of 5)
    needs: [compilation]
    uses: ./.github/workflows/run-unit-tests-group.yml
    with:
      group_id: 1
      num_groups: 5

  unit-tests-group-2:
    name: Run unit tests (2 of 5)
    needs: [compilation]
    uses: ./.github/workflows/run-unit-tests-group.yml
    with:
      group_id: 2
      num_groups: 5

  unit-tests-group-3:
    name: Run unit tests (3 of 5)
    needs: [compilation]
    uses: ./.github/workflows/run-unit-tests-group.yml
    with:
      group_id: 3
      num_groups: 5

  unit-tests-group-4:
    name: Run unit tests (4 of 5)
    needs: [compilation]
    uses: ./.github/workflows/run-unit-tests-group.yml
    with:
      group_id: 4
      num_groups: 5

  unit-tests-group-5:
    name: Run unit tests (5 of 5)
    needs: [compilation]
    uses: ./.github/workflows/run-unit-tests-group.yml
    with:
      group_id: 5
      num_groups: 5

  aggregate-all:
    name: compile and test the project
    runs-on: ubuntu-latest
    needs: [compilation, unit-tests-group-1, unit-tests-group-2, unit-tests-group-3, unit-tests-group-4, unit-tests-group-5]
    if: ${{ always() }} # do not skip if one of the actions above has failed!
    env:
      everything_ok: ${{ !contains(needs.*.result, 'failure') && (!contains(needs.*.result, 'skipped') || needs.compilation.result == 'skipped') }}
    steps:
      - name: The workflow has succeeded
        if: ${{ env.everything_ok == 'true' }}
        run: exit 0
      - name: The workflow has failed
        if: ${{ env.everything_ok == 'false' }}
        run: exit 1
