on:
  workflow_call:
    inputs:
      group_id:
        required: true
        type: string
      num_groups:
        required: true
        type: string
  
  jobs:
    run_unit_tests_group:
      name: tests
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup-scala
        - uses: ./.github/actions/restore-compilation-cache
        - run: docker compose -f ./deployment/local/docker-compose.yml up -d
        - name: Unit tests
          run: sbt 'parTestGroup ${{ inputs.group_id }} ${{ inputs.num_groups }}'

  